st-charts:
  - name: harness-delegate-ng
    version: 1.0.25
    dependencies:
      - name: harness-delegate-ng
        version: 1.0.25
        repository: https://app.harness.io/storage/harness-download/delegate-helm-chart/
