apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: headlamp-token
  namespace: headlamp
  annotations:
    kubernetes.io/service-account.name: headlamp
    kubernetes.io/service-account.namespace: headlamp
