st-charts:
  - name: kuberay-operator
    version: 1.3.2
    dependencies:
      - name: kuberay-operator
        version: 1.3.2
        repository: https://ray-project.github.io/kuberay-helm/
  - name: ray-cluster
    version: 1.3.2
    dependencies:
      - name: ray-cluster
        version: 1.3.2
        repository: https://ray-project.github.io/kuberay-helm/
