apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: runai-control-plane-2-21-17
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: runai-control-plane
      version: 2.21.17
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-catalog
