jupyterhub:
  jupyterhub:
    ingress:
      enabled: true
      hosts: ['']

traefik:
  traefik:
    deployment:
      kind: DaemonSet
    ports:
      web:
        port: 8000
        hostPort: 80
      websecure:
        port: 8443
        hostPort: 443

ollama:
  ollama:
    models:
      pull: [smollm:135m]
      run: [smollm:135m]
