apiVersion: v2
name: rabbitmq
description: A Helm chart that references the official "rabbitmq" Helm chart.
type: application
version: 0.1.0
dependencies:
  - name: rabbitmq
    version: 0.1.0
    repository: oci://registry-1.docker.io/cloudpirates
