apiVersion: k0rdent.mirantis.com/v1alpha1
kind: MultiClusterService
metadata:
  name: dex
spec:
  clusterSelector:
    matchLabels:
      group: demo
  serviceSpec:
    services:
      - template: dex-0-19-1
        name: dex
        namespace: dex
        values: |
          dex:
            config:
              issuer: https://dex.tunnelto.dev/dex
              storage:
                type: memory
              connectors:
                - type: mockCallback
                  id: mock
                  name: Example
