apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ required "A valid 'repository.name' value is required!" .Values.repository.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    k0rdent.mirantis.com/managed: "true"
  annotations:
    helm.sh/resource-policy: keep
spec:
  type: {{ .Values.repository.type }}
  url: {{ required "A valid 'helm.repository.url' value is required!" .Values.repository.url }}
